### ISSUE TITLE
`get_dominant_color` method

### ISSUE THREAD

**Issue by baseplate-admin** [RazrFalcon/color-thief-rs#7]
Hi, Is it possible to expose `get_dominant_color` method ?

`fast-colortheif` exposes it like this 
https://github.com/bedapisl/fast-colorthief/blob/92eda78157bed309ef9c12e85708ae21241e11d0/fast_colorthief.py#L9-L22

**Comment by RazrFalcon** [comment]
Isn't this just `get_palette[0]`?

**Comment by baseplate-admin** [comment]
Hi, if this is the case, could this be documented?

**Comment by RazrFalcon** [comment]
It is:

>Differences
There is no getColor method, since it's [just a shorthand](https://github.com/lokesh/color-thief/blob/b0115131476149500828b01db43ca701b099a315/src/color-thief.js#L76) for getPalette.

And your Python variant called `getColor` as `get_dominant_color`. But this is JS code port, not Python one.

**Comment by baseplate-admin** [comment]
Thanks for your input on this
